backend:
  name: github
  branch: connecting-firebase
  repo: nascent-works/nascent-works.github.io
  identity_url: "https://nascent-works.com/.netlify/identity"
  gateway_url: "https://nascent-works.com/.netlify/git"
  squash_merges: true
  base_url: https://us-central1-nascent-home.cloudfunctions.net
  auth_endpoint: /oauth/auth

local_backend: true

publish_mode: editorial_workflow

media_folder: assets/img
public_folder: assets/img

collections:
  - label: "Services"
    name: "services"
    editor:
      preview: true
    files:
      - label: "Service"
        name: Service
        file: "_data/services.yml"
        create: true
        fields:
          - label: "Services items"
            name: "servicesItems"
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "string" }
              - { label: "Icon", name: "icon", widget: image, required: true  }
  - label: "Careers"
    name: "careers"
    editor:
      preview: true
    files:
      - label: "Position"
        name: position
        file: "_data/careers.yml"
        create: true
        fields:
          - label: "Position items"
            name: "positionItems"
            widget: list
            fields:
              - { label: "Position name", name: "position", widget: "string" }
              - label: "Position requirements"
                name: positionRequirements
                widget: list
                fields:
                  - {label: "Requirement item", name: positionRequirement, widget: string}
              - label: "Additional requirements"
                name: additionalRequirements
                widget: list
                fields:
                  - {label: "Requirement item", name: additionalRequirement, widget: string}
              - label: "Job description"
                name: jobDescription
                widget: list
                fields:
                  - {label: "Description item", name: descriptionItem, widget: string}
              - label: "We offer"
                name: weOffer
                widget: list
                fields:
                  - {label: "We offer item", name: weOfferItem, widget: string}